 $(function(){
	$(".wq_wyone_down").hover(function(){
     $(this).css({
		"font-size":"18",
		"padding-left":25
		 })
	},function(){
		$(this).css({
		"font-weight":"16",
		"padding-left":30
		 })
	})
	$(".wq_wyone_read").hover(function(){
     $(this).css({
		"margin-right":25
		 })
	},function(){
		$(this).css({
		"margin-right":20
		 })
	})  
	 })